execute pathogen#infect()
execute pathogen#helptags()

set laststatus=2

" make backspace work like most other apps
set backspace=indent,eol,start

" set termguicolors
set term=screen-256color
syntax enable
set background=dark
colorscheme gruvbox

set relativenumber

" reload vim when change is made
augroup reload_vimrc
    autocmd!
    autocmd BufWritePost $MYVIMRC source $MYVIMRC
augroup END

" turn on column numbering
set number

" use indentation of previous line
set autoindent

" use intelligent indentation for C
set smartindent

" tab width is 4 spaces
set tabstop=4        
set softtabstop=4

set shiftwidth=4 

" highlight matching braces
set showmatch

" show whitespace
set list

" change the character displayed for newline and tab
set listchars=tab:▸\ ,eol:¬

" disable vi compatibility
set nocompatible

" provide Python 3 completion with YCM
let g:ymc_python_binary_path = '/usr/bin/python3'

" syntastic
set statusline+=%#warningmsg#
set statusline+=%{SyntasticStatuslineFlag()}
set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list = 1
let g:syntastic_check_on_open = 1
let g:syntastic_check_on_wq = 0

let g:syntastic_python_python_exec = '/usr/bin/python3'

